### ISSUE TITLE
action takes ~50 seconds to build

### ISSUE THREAD

**Issue by staabm** [mattermost/action-mattermost-notify#10]
the action takes ~50 seconds to build.

in comparison to using a plain curl call in the github action this overhead is crazy

![grafik](https://user-images.githubusercontent.com/120441/128490117-4eb05993-2215-4b82-8cac-f8721f995939.png)

**Comment by cpanato** [comment]
I will check if we can use a built image instead of building everytime one

**Comment by N0N4M3BNS** [comment]
My side still same issues, take so long to build 
<img width="875" alt="image" src="https://user-images.githubusercontent.com/56629789/159880172-2c46ce63-ee7e-443b-9220-a2ac480c6aef.png">

**Comment by toninis** [comment]
Fixed: https://github.com/mattermost/action-mattermost-notify/pull/13
