### ISSUE TITLE
cannot find package "github.com/mattermost/mattermost-server/v5/model"

### ISSUE THREAD

**Issue by donjetam** [mattermost/action-mattermost-notify#7]
Build container for action use: '/runner/_work/_actions/mattermost/action-mattermost-notify/master/Dockerfile'.
  /usr/local/bin/docker build -t 60e226:220ad6d212c0422aa68464ae940599ec -f "/runner/_work/_actions/mattermost/action-mattermost-notify/master/Dockerfile" "/runner/_work/_actions/mattermost/action-mattermost-notify/master"
  Sending build context to Docker daemon  65.02kB
  
  Step 1/11 : FROM golang:1.14
  1.14: Pulling from library/golang
  0ecb575e629c: Pulling fs layer
  7467d1831b69: Pulling fs layer
  feab2c490a3c: Pulling fs layer
  f15a0f46f8c3: Pulling fs layer
  1517911a35d7: Pulling fs layer
  48bbd1746d63: Pulling fs layer
  944903612fdd: Pulling fs layer
  f15a0f46f8c3: Waiting
  1517911a35d7: Waiting
  48bbd1746d63: Waiting
  944903612fdd: Waiting
  feab2c490a3c: Download complete
  7467d1831b69: Verifying Checksum
  7467d1831b69: Download complete
  0ecb575e629c: Download complete
  f15a0f46f8c3: Verifying Checksum
  f15a0f46f8c3: Download complete
  1517911a35d7: Verifying Checksum
  1517911a35d7: Download complete
  944903612fdd: Verifying Checksum
  944903612fdd: Download complete
  48bbd1746d63: Verifying Checksum
  48bbd1746d63: Download complete
  0ecb575e629c: Pull complete
  7467d1831b69: Pull complete
  feab2c490a3c: Pull complete
  f15a0f46f8c3: Pull complete
  1517911a35d7: Pull complete
  48bbd1746d63: Pull complete
  944903612fdd: Pull complete
  Digest: sha256:1a7173b5b9a3af3e29a5837e0b2027e1c438fd1b83bbee8f221355087ad416d6
  Status: Downloaded newer image for golang:1.14
   ---> 21a5635903d6
  Step 2/11 : LABEL version="1.0.2"
   ---> Running in b9b3cc309110
  Removing intermediate container b9b3cc309110
   ---> 4604fc9d1b48
  Step 3/11 : LABEL maintainer="mattermost"
   ---> Running in cf4776f39ef1
  Removing intermediate container cf4776f39ef1
   ---> afb1f72e14f2
  Step 4/11 : LABEL repository="http://github.com/mattermost/action-mattermost-notify"
   ---> Running in 3390a9a8b70f
  Removing intermediate container 3390a9a8b70f
   ---> 39bbf90f4e7c
  Step 5/11 : LABEL homepage="http://github.com/mattermost/action-mattermost-notify"
   ---> Running in c086fe952d34
  Removing intermediate container c086fe952d34
   ---> 240233c1e2a0
  Step 6/11 : LABEL "com.github.actions.name"="Mattermost"
   ---> Running in 27697b576da7
  Removing intermediate container 27697b576da7
   ---> 4c7b6536b9e7
  Step 7/11 : LABEL "com.github.actions.description"="Send a Mattermost message"
   ---> Running in f8eedaedd567
  Removing intermediate container f8eedaedd567
   ---> b0bb48b625f5
  Step 8/11 : LABEL "com.github.actions.icon"="send"
   ---> Running in a8e6912316f3
  Removing intermediate container a8e6912316f3
   ---> 8a88f42670db
  Step 9/11 : LABEL "com.github.actions.color"="blue"
   ---> Running in 4add31482281
  Removing intermediate container 4add31482281
   ---> a3584aa9cdf6
  Step 10/11 : RUN go get github.com/mattermost/action-mattermost-notify
   ---> Running in 44feb92d3171
  package github.com/mattermost/mattermost-server/v5/model: cannot find package "github.com/mattermost/mattermost-server/v5/model" in any of:
  	/usr/local/go/src/github.com/mattermost/mattermost-server/v5/model (from $GOROOT)
  	/go/src/github.com/mattermost/mattermost-server/v5/model (from $GOPATH)
  The command '/bin/sh -c go get github.com/mattermost/action-mattermost-notify' returned a non-zero code: 1

**Comment by cpanato** [comment]
thanks for the issue, i will check and get this fixed

**Comment by nickboldt** [comment]
Is this because there's no v5 release/tag/branch, but there is a https://github.com/mattermost/mattermost-server/tree/v5.26.0 and the latest release is https://github.com/mattermost/mattermost-server/releases/tag/v5.37.0 ? 

Do you need a floating tag or branch located at https://github.com/mattermost/mattermost-server/tree/v5 that points to the latest code, so that notify 1.0.4 can resolve sources from server v5? 

Or should the code in this repo be pinned to a specific server version like v5.2.6.0 or v5.37.0, rather than just v5?

**Comment by donjetam** [comment]
> Is this because there's no v5 release/tag/branch, but there is a https://github.com/mattermost/mattermost-server/tree/v5.26.0 and the latest release is https://github.com/mattermost/mattermost-server/releases/tag/v5.37.0 ?
> 
> Do you need a floating tag or branch located at https://github.com/mattermost/mattermost-server/tree/v5 that points to the latest code, so that notify 1.0.4 can resolve sources from server v5?
> 
> Or should the code in this repo be pinned to a specific server version like v5.2.6.0 or v5.37.0, rather than just v5?

Second suggestion looks good. Can you please do the changes?

**Comment by nickboldt** [comment]
To which version would you like the pin? latest stable release 5.37.0? or latest branched release 5.26.0?

**Comment by donjetam** [comment]
Latest realse v5.37.0 it will be fine.

**Comment by ghost** [comment]
Having the same issue on our end

**Comment by nickboldt** [comment]
PR that might fix this: https://github.com/mattermost/action-mattermost-notify/pull/8 (needs approval by the Mattermost Gods).

**Comment by cpanato** [comment]
https://github.com/mattermost/action-mattermost-notify/pull/8 should fix it

**Comment by donjetam** [comment]
After Im using new tag @1.0.3, I have these error message
```
Run mattermost/action-mattermost-notify@1.0.3
/usr/local/bin/docker run --name e226b722a4416b624493b7808ea54a5d94f3_f8f3e0 --label 60e226 --workdir /github/workspace --rm -e APPLICATION_NAME -e MATTERMOST_WEBHOOK_URL -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/runner/_work/_temp/_github_home":"/github/home" -v "/runner/_work/_temp/_github_workflow":"/github/workflow" -v "/runner/_work/_temp/_runner_file_commands":"/github/file_commands" -v "/runner/_work/github-action-test/github-action-test":"/github/workspace" 60e226:b722a4416b624493b7808ea54a5d94f3
2021/07/26 13:12:05 error sending message: requesting: Post "***": x509: certificate signed by unknown authority
```

**Comment by nickboldt** [comment]
Hmmm. Maybe we should stick with an alpine base image instead of switching to scratch? I hadn't considered that other files in the container are being used (eg., certificates).  WDYT @cpanato  ?

**Comment by cpanato** [comment]
thanks for let us know

tested with 1.03 and confirmed that is not working and I've made a change and it is working now
https://github.com/cpanato/testing-ci-providers/runs/3162121062?check_suite_focus=true

will open a PR shortly

**Comment by nickboldt** [comment]
Will you be able to re-release 1.0.3 with this fix, or will this require a 1.0.4 ?

**Comment by cpanato** [comment]
will need a new release

**Comment by cpanato** [comment]
released https://github.com/mattermost/action-mattermost-notify/releases/tag/1.1.0
